# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preliminary_event_display.ui'
#
# Created by: PyQt5 UI code generator 5.8.1.dev1702270917
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AraEventDisplay(object):
    def setupUi(self, AraEventDisplay):
        AraEventDisplay.setObjectName("AraEventDisplay")
        AraEventDisplay.resize(867, 615)
        self.graphicsView = QtWidgets.QGraphicsView(AraEventDisplay)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 541, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.line = QtWidgets.QFrame(AraEventDisplay)
        self.line.setGeometry(QtCore.QRect(560, 0, 20, 611))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton.setGeometry(QtCore.QRect(600, 100, 71, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 150, 71, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_9.setGeometry(QtCore.QRect(600, 200, 71, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_10.setGeometry(QtCore.QRect(600, 250, 71, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_11.setGeometry(QtCore.QRect(710, 100, 71, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_12.setGeometry(QtCore.QRect(710, 150, 71, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_13.setGeometry(QtCore.QRect(710, 200, 71, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_14.setGeometry(QtCore.QRect(710, 250, 71, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.line_2 = QtWidgets.QFrame(AraEventDisplay)
        self.line_2.setGeometry(QtCore.QRect(570, 30, 291, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(AraEventDisplay)
        self.label.setGeometry(QtCore.QRect(580, 50, 161, 31))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(AraEventDisplay)
        self.line_3.setGeometry(QtCore.QRect(570, 310, 281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.comboBox = QtWidgets.QComboBox(AraEventDisplay)
        self.comboBox.setGeometry(QtCore.QRect(180, 400, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(AraEventDisplay)
        self.label_2.setGeometry(QtCore.QRect(50, 400, 131, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 440, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 440, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(AraEventDisplay)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 440, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(AraEventDisplay)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 161, 31))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(AraEventDisplay)
        self.textBrowser.setGeometry(QtCore.QRect(575, 350, 281, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(AraEventDisplay)
        QtCore.QMetaObject.connectSlotsByName(AraEventDisplay)

    def retranslateUi(self, AraEventDisplay):
        _translate = QtCore.QCoreApplication.translate
        AraEventDisplay.setWindowTitle(_translate("AraEventDisplay", "AraEventDisplay"))
        self.pushButton.setText(_translate("AraEventDisplay", "Ch1"))
        self.pushButton_2.setText(_translate("AraEventDisplay", "Ch2"))
        self.pushButton_9.setText(_translate("AraEventDisplay", "Ch3"))
        self.pushButton_10.setText(_translate("AraEventDisplay", "Ch4"))
        self.pushButton_11.setText(_translate("AraEventDisplay", "Ch5"))
        self.pushButton_12.setText(_translate("AraEventDisplay", "Ch6"))
        self.pushButton_13.setText(_translate("AraEventDisplay", "Ch7"))
        self.pushButton_14.setText(_translate("AraEventDisplay", "Ch8"))
        self.label.setText(_translate("AraEventDisplay", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Plot Waveform</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("AraEventDisplay", "1002"))
        self.comboBox.setItemText(1, _translate("AraEventDisplay", "1040"))
        self.comboBox.setItemText(2, _translate("AraEventDisplay", "8726"))
        self.comboBox.setItemText(3, _translate("AraEventDisplay", "8241"))
        self.comboBox.setItemText(4, _translate("AraEventDisplay", "1000"))
        self.comboBox.setItemText(5, _translate("AraEventDisplay", "7653"))
        self.label_2.setText(_translate("AraEventDisplay", "Start Event Number"))
        self.pushButton_3.setText(_translate("AraEventDisplay", "Save As PDF"))
        self.pushButton_4.setText(_translate("AraEventDisplay", "Save as jpeg"))
        self.pushButton_5.setText(_translate("AraEventDisplay", "Save As png"))
        self.label_3.setText(_translate("AraEventDisplay", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Ara Event Display</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AraEventDisplay = QtWidgets.QDialog()
    AraEventDisplay.setWindowTitle("AraEventDisplay")
    ui = Ui_AraEventDisplay()
    ui.setupUi(AraEventDisplay)
    AraEventDisplay.show()
    sys.exit(app.exec_())

